spring:
  application:
    name: Edu-Tracking-System

  #Databse Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/ets_db?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#Application properties
super_admin:
  email: ${SUPER-ADMIN.EMAIL}